package com.esp.entity;
// Generated Jul 18, 2014 3:06:38 PM by Hibernate Tools 3.6.0



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Answertypemaster generated by hbm2java
 */
@Entity
@Table(name="ANSWERTYPEMASTER"
    ,schema="SURVEY"
)
public class Answertypemaster  implements java.io.Serializable {


     private Integer anstypemasterid;
     private String description;
     private Set<Questionanswermapping> questionanswermappings = new HashSet<Questionanswermapping>(0);

    public Answertypemaster() {
    }

	
    public Answertypemaster(Integer anstypemasterid) {
        this.anstypemasterid = anstypemasterid;
    }
    public Answertypemaster(Integer anstypemasterid, String description, Set<Questionanswermapping> questionanswermappings) {
       this.anstypemasterid = anstypemasterid;
       this.description = description;
       this.questionanswermappings = questionanswermappings;
    }
   
     @Id 

    
    @Column(name="ANSTYPEMASTERID", unique=true, nullable=false, precision=22, scale=0)
    public Integer getAnstypemasterid() {
        return this.anstypemasterid;
    }
    
    public void setAnstypemasterid(Integer anstypemasterid) {
        this.anstypemasterid = anstypemasterid;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="answertypemaster")
    public Set<Questionanswermapping> getQuestionanswermappings() {
        return this.questionanswermappings;
    }
    
    public void setQuestionanswermappings(Set<Questionanswermapping> questionanswermappings) {
        this.questionanswermappings = questionanswermappings;
    }




}


