package com.esp.entity;
// Generated Jul 18, 2014 3:06:38 PM by Hibernate Tools 3.6.0



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Questionmaster generated by hbm2java
 */
@Entity
@Table(name="QUESTIONMASTER"
    ,schema="SURVEY"
)
public class Questionmaster  implements java.io.Serializable {


     private Integer questionid;
     private Usermaster usermasterByCreatedbyid;
     private Usermaster usermasterByLastmodifiedbyid;
     private String questiontext;
     private String createdbyname;
     private Date createddate;
     private Date lastmodifieddate;
     private String lastmodifiedbyname;
     private Set<Questionanswermapping> questionanswermappings = new HashSet<Questionanswermapping>(0);

    public Questionmaster() {
    }

	
    public Questionmaster(Integer questionid, String questiontext) {
        this.questionid = questionid;
        this.questiontext = questiontext;
    }
    public Questionmaster(Integer questionid, Usermaster usermasterByCreatedbyid, Usermaster usermasterByLastmodifiedbyid, String questiontext, String createdbyname, Date createddate, Date lastmodifieddate, String lastmodifiedbyname, Set<Questionanswermapping> questionanswermappings) {
       this.questionid = questionid;
       this.usermasterByCreatedbyid = usermasterByCreatedbyid;
       this.usermasterByLastmodifiedbyid = usermasterByLastmodifiedbyid;
       this.questiontext = questiontext;
       this.createdbyname = createdbyname;
       this.createddate = createddate;
       this.lastmodifieddate = lastmodifieddate;
       this.lastmodifiedbyname = lastmodifiedbyname;
       this.questionanswermappings = questionanswermappings;
    }
   
     @Id 

    
    @Column(name="QUESTIONID", unique=true, nullable=false, precision=22, scale=0)
    public Integer getQuestionid() {
        return this.questionid;
    }
    
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CREATEDBYID")
    public Usermaster getUsermasterByCreatedbyid() {
        return this.usermasterByCreatedbyid;
    }
    
    public void setUsermasterByCreatedbyid(Usermaster usermasterByCreatedbyid) {
        this.usermasterByCreatedbyid = usermasterByCreatedbyid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LASTMODIFIEDBYID")
    public Usermaster getUsermasterByLastmodifiedbyid() {
        return this.usermasterByLastmodifiedbyid;
    }
    
    public void setUsermasterByLastmodifiedbyid(Usermaster usermasterByLastmodifiedbyid) {
        this.usermasterByLastmodifiedbyid = usermasterByLastmodifiedbyid;
    }

    
    @Column(name="QUESTIONTEXT", nullable=false, length=200)
    public String getQuestiontext() {
        return this.questiontext;
    }
    
    public void setQuestiontext(String questiontext) {
        this.questiontext = questiontext;
    }

    
    @Column(name="CREATEDBYNAME", length=200)
    public String getCreatedbyname() {
        return this.createdbyname;
    }
    
    public void setCreatedbyname(String createdbyname) {
        this.createdbyname = createdbyname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATEDDATE", length=7)
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LASTMODIFIEDDATE", length=7)
    public Date getLastmodifieddate() {
        return this.lastmodifieddate;
    }
    
    public void setLastmodifieddate(Date lastmodifieddate) {
        this.lastmodifieddate = lastmodifieddate;
    }

    
    @Column(name="LASTMODIFIEDBYNAME", length=200)
    public String getLastmodifiedbyname() {
        return this.lastmodifiedbyname;
    }
    
    public void setLastmodifiedbyname(String lastmodifiedbyname) {
        this.lastmodifiedbyname = lastmodifiedbyname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questionmaster")
    public Set<Questionanswermapping> getQuestionanswermappings() {
        return this.questionanswermappings;
    }
    
    public void setQuestionanswermappings(Set<Questionanswermapping> questionanswermappings) {
        this.questionanswermappings = questionanswermappings;
    }




}


