package com.esp.entity;
// Generated Jul 18, 2014 3:06:38 PM by Hibernate Tools 3.6.0



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Surveytypemaster generated by hbm2java
 */
@Entity
@Table(name="SURVEYTYPEMASTER"
    ,schema="SURVEY"
)
public class Surveytypemaster  implements java.io.Serializable {


     private Integer surveytypeid;
     private String surveytype;
     private Set<Surveymaster> surveymasters = new HashSet<Surveymaster>(0);

    public Surveytypemaster() {
    }

	
    public Surveytypemaster(Integer surveytypeid) {
        this.surveytypeid = surveytypeid;
    }
    public Surveytypemaster(Integer surveytypeid, String surveytype, Set<Surveymaster> surveymasters) {
       this.surveytypeid = surveytypeid;
       this.surveytype = surveytype;
       this.surveymasters = surveymasters;
    }
   
     @Id    
    @Column(name="SURVEYTYPEID", unique=true, nullable=false, precision=22, scale=0)
    public Integer getSurveytypeid() {
        return this.surveytypeid;
    }
    
    public void setSurveytypeid(Integer surveytypeid) {
        this.surveytypeid = surveytypeid;
    }

    
    @Column(name="SURVEYTYPE", length=200)
    public String getSurveytype() {
        return this.surveytype;
    }
    
    public void setSurveytype(String surveytype) {
        this.surveytype = surveytype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="surveytypemaster")
    public Set<Surveymaster> getSurveymasters() {
        return this.surveymasters;
    }
    
    public void setSurveymasters(Set<Surveymaster> surveymasters) {
        this.surveymasters = surveymasters;
    }




}


