package com.esp.entity;
// Generated Jul 18, 2014 3:06:38 PM by Hibernate Tools 3.6.0



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userlist generated by hbm2java
 */
@Entity
@Table(name="USERLIST"
    ,schema="SURVEY"
)
public class Userlist  implements java.io.Serializable {


     private Integer userlistid;
     private Usermaster usermaster;
     private Organisation organisation;
     private String userlistname;

    public Userlist() {
    }

	
    public Userlist(Integer userlistid) {
        this.userlistid = userlistid;
    }
    public Userlist(Integer userlistid, Usermaster usermaster, Organisation organisation, String userlistname) {
       this.userlistid = userlistid;
       this.usermaster = usermaster;
       this.organisation = organisation;
       this.userlistname = userlistname;
    }
   
     @Id 

    
    @Column(name="USERLISTID", unique=true, nullable=false, precision=22, scale=0)
    public Integer getUserlistid() {
        return this.userlistid;
    }
    
    public void setUserlistid(Integer userlistid) {
        this.userlistid = userlistid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERID")
    public Usermaster getUsermaster() {
        return this.usermaster;
    }
    
    public void setUsermaster(Usermaster usermaster) {
        this.usermaster = usermaster;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORGID")
    public Organisation getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

    
    @Column(name="USERLISTNAME", length=20)
    public String getUserlistname() {
        return this.userlistname;
    }
    
    public void setUserlistname(String userlistname) {
        this.userlistname = userlistname;
    }




}


